### PR TITLE
Incorporate into master

### PR DESCRIPTION
**Pull request by sevu**
Included @Lukc changes, finished translation, the dwarf bug seems to be 10 months old.

@Robertdebrus Ready to be uploaded.

Please, both, configure your editor to save files in utf8 encoding and to use spaces instead of tabs (or run wmlindent before committing). Otherwise this causes huge problems with merging or introduces bugs.
If the commits show the file as binary or show a diff where nothing visibly changed in the line, it's likely broken.

### CODE REVIEW

**Comment by rwallac** [comment]
Should I merge this before or after the other one, or does it matter? Sorry for not being able to pay attention much the past few days!

**Comment by sevu** [comment]
Instead of the other, I already merged the other into this one.

No worries, just please have a look at setting your editor to use utf8 =)

As for releasing, #40 needs to be fixed before (probably trivial), otherwise it looks fine.

**Comment by rwallac** [comment]
I will look at my editor settings!

**Comment by Lukc** [comment]
Thanks a lot for fixing the merge!

For the wmllint/(tabs/space) issue, couldn’t things like that be checked automatically with CI? Maybe you know if another UMC project does something similar?

**Comment by sevu** [comment]
I don't know if there exist continuous integration for that, and how hard it is to set up.
Given the size of this project, it's probably easier to set up the editor.

**Comment by Lukc** [comment]
The editor fix is indeed easier. Having a CI infrastructure setup would be a good start for any kind of additional automated testing, though.

What about adding (Vim?) modelines to the files?

**Comment by sevu** [comment]
It would be, the tests could be
- [ ] It could test if the code still runs, using the wesnoth executable with  `--preprocess`
- [ ] Search for tabs, maybe check for the return of:  grep $'\t' | wc -l
- [ ] Search for non-unicode strings: maybe similar – or run wmlindent which crashes with non-unicode input:stuck_out_tongue:
- [ ] Testing if there are translatable strings in the wrong textdomain. In theory that could mean, finding all strings from the *.cfg files, regenerate the ANLEra's translation file (basically the wmlxgettext line from the makefile) and to look for each found string if it is in any of the games or the add-ons translation file listed – if not it's unknown. In practice, I wonder how to compare them, as the PO formats wraps all strings at 80 characters.
Another idea would be to regenerate the mainline translations files, and look one of them has more strings than before, meaning one of our ones ended up there.
- [ ] since we're anyway at it, we can run wmllint and warn if it outputs anything.


For modlines, I didn't use them, but I have no objections either, would be ~50 files.

**Pull request merged**
