### PR TITLE
Fixes for issues I introduced.

### PR DESCRIPTION
**Pull request by Lukc**
At the moment this includes a fix for the AI having lost their extra recruits. It also provides them with a longer list of recruits, starting at the same turns as the ANL scenario AIs.

I’ll probably commit code for other things though.

PS: Please don’t squash/rebase when you merge. It breaks everyone’s histories and makes further merge requests more complicated.

### CODE REVIEW

**Comment by sevu** [comment]
@Robertdebrus I think the best way to merge this is to do it manually.
If you scroll down there are command line instructions listed, though I don't know how fitting they are. What I usually do:
1) check out some commit before the first in the PR ( `git checkout commit-ID`)
2) make a new branch from it ( `git branch somename`)(or add the `-b` argument in 1))
3) `git pull https://github.com/Lukc/ANLEra.git master`
then you have the changes somewhere in your git
4) switch to master
5) cherry-pick the commits, with `git cherry-pick commit-ID`. (They will have another ID afterwards, but that's fine)

@Lukc It's mostly easier if one works in a branch, and keeps master free. One can always work around things though, you could
1) check out some commit before the first in the PR ( `git checkout commit-ID`)
2) make a new branch from it ( `git branch somename`)(or add the `-b` argument in 1))
3) rebase it to upstream (let's assume you called this repo `upstream` and your one `fork`) `git rebase upstream/master`
4) cherry-pick the new commits from your local (or your forks) master branch.

**Comment by rwallac** [comment]
Hey, sorry for not being available the past few days. I followed the command line instructions, but nothing seems to have happened?

**Comment by Lukc** [comment]
@sevu, I guess I can close this if you integrated it into your own PR? Or are some commits still missing?

**Comment by sevu** [comment]
Can be closed, all commits are merged.

**Comment by rwallac** [comment]
Alright

**Pull request closed without merging**
