### PR TITLE
Update ANLEra.cfg

### PR DESCRIPTION
**Pull request by sevu**

### CODE REVIEW

**Comment by rwallac** [comment]
I'm not familiar with hide-help, could you tell my why should this be there?

**Comment by sevu** [comment]
In the help there is in the sidebar an entry for eras, where they are listed alongside with their respective factions. I think it is new in 1.13.
As ANL is not a real era, I tend to not list it. If it should be there, it needs a proper description.

**Comment by rwallac** [comment]
Ah, that makes sense!

**Comment by rwallac** [comment]
I'll upload it when I get home in a few hours!

**Pull request merged**
